### ISSUE TITLE
Spiders fail to process jobs with existing organisations

### ISSUE THREAD

**Issue by ojongerius** [volCommunity/vol-crawlers#48]
This is fallout from migrating to the new REST API. ( https://github.com/volCommunity/vol-django/pull/86 ) 2 issues:

* Crawler: Pipeline.py encounters a key error, looking for the organisation ID, something that the new API no longer returns 
* Django: The API accepts fields that are not used, which is misleading. We need to invest a little time in creating and or calling validation of the whole request. I expected the built in validator would take care of this.

Error message at Scrapinghub:
```
[scrapy.core.scraper] Error processing {'api_url': 'https://api.do-it.org', Less
 'city': 'Unknown',
 'country': 'UK',
 'labels': ['Education', 'Animals'],
 'organisation': 'Cumbria CVS - Volunteer Centre',
 'organisation_url': '/v2/orgs/cumbria-cvs-volunteer-centre',
 'region': 'placeholder',
 'site_name': 'Do It',
 'site_url': 'https://do-it.org',
 'sites': ['Do It'],
 'text': 'As an Education Speaker you will act as an ambassador for Cats '
         'Protection and play a key role in raising awareness of how the '
         'charity makes a big difference to the lives of thousands of cats and '
         'kittens in need each year. You will inspire others, develop learning '
         'and understanding of feline welfare and be the voice for cats in '
         'your community. \n'
         'The role involves\n'
         '•\tGiving talks to schools and community groups\n'
         '•\tHolding information sessions for local groups \n'
         '•\tWorking closely with your Community Education Officer \n'
         '•\tCompleting activity evaluations and feedback forms\n'
         '•\tBeing a positive representative for Cats Protection in your '
         'community\n'
         '\n'
         'This is a very flexible role; from one workshop a week to one '
         'workshop a month. A full induction and training will be provided '
         'along with a range of resources.',
 'title': 'Cats Protection - Cumbria - Education Speakers across Cumbria',
 'url': 'https://do-it.org/#/opportunities/44b8ae2f-5dde-4937-b19d-d27c355b3e7e'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/app/__main__.egg/vol/pipelines.py", line 87, in process_item
KeyError: 'id'
``` 

- [x] Fix bug in crawlers
- [x] Re-enable spiders

**Comment by ojongerius** [comment]
Should be fixed in #49
